name: khatma
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^1.0.6

  # https://pub.dev/packages/sqflite
  sqflite: ^2.3.2

  # https://pub.dev/packages/get
  get: ^4.6.6
  
  # https://pub.dev/packages/flutter_localization
  flutter_localization: ^0.2.0

  # https://pub.dev/packages/scrollable_positioned_list
  scrollable_positioned_list: ^0.3.8

  # https://pub.dev/packages/share_plus
  share_plus: ^7.2.2

  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.2.4

  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.2.2

  # https://pub.dev/packages/firebase_messaging
  firebase_messaging: ^14.7.15

  # https://pub.dev/packages/cloud_firestore
  cloud_firestore: ^4.15.4

  # https://pub.dev/packages/anim_search_bar
  anim_search_bar: ^2.0.3
  
  # https://pub.dev/packages/flutter_splash_screen
  flutter_splash_screen: ^2.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-Regular.ttf
        - asset: assets/fonts/ElMessiri-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ElMessiri-Bold.ttf
          weight: 700
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/ElMessiri-Bold.ttf
          weight: 700
    - family: quran
      fonts:
        - asset:  assets/fonts/HafsSmart_08.ttf
    - family: me_quran
      fonts:
        - asset:  assets/fonts/me_quran.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
